name: Secret Detection
on:
  pull_request:
    branches: [ main ]

jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install detect-secrets
        run: pip install detect-secrets==1.4.0
      
      - name: Run secret detection
        run: |
          detect-secrets scan --all-files > secrets.json || echo "Scan completed"
          if [ -s secrets.json ]; then
            echo "Secrets found! Check secrets.json"
            cat secrets.json
            exit 1
          fi
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: secrets-report
          path: secrets.json