name: CI Pipeline for BankingSystem
on:
  pull_request:
    branches: [ main ]
jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Detect secrets
      uses: madhuakula/detect-secrets-action@v0.1.0
      with:
        fail-on-secrets: true
        scan-path: .
    
    - name: Upload secrets report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: secrets-report
        path: secrets.json
