name: 'Secret Detection on PR'
description: 'Scans Pull Requests for accidentally committed secrets and exports findings as artifact'
on:
  pull_request:
    branches: [ main ]

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to properly scan the changes in the PR

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install detect-secrets
        run: |
          pip install detect-secrets
          pip install jq

      - name: Create baseline if not exists
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
            mkdir empty-dir
            detect-secrets scan empty-dir > .secrets.baseline
            echo "✅ Blank .secrets.baseline file created successfully."
            rm -r empty-dir
          else
            echo "✅ Existing .secrets.baseline file detected."
          fi

      - name: Scan for secrets
        run: |
          # Scan the repository for secrets
          detect-secrets scan --all-files --baseline .secrets.baseline --exclude-files '.secrets.*' --exclude-files '.git*' > secrets.json
          
          # Count the number of secrets found
          SECRETS_COUNT=$(jq '.results | length' secrets.json)
          echo "Found $SECRETS_COUNT potential secrets"

          # Save the results as artifact
          echo "SECRETS_COUNT=$SECRETS_COUNT" >> $GITHUB_ENV

      - name: Upload secrets report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: secrets-detection-report
          path: secrets.json
          if-no-files-found: warn

      - name: Fail if secrets found
        if: env.SECRETS_COUNT != '0'
        run: |
          echo "::error::Potential secrets detected in the code. Check the artifacts for details."
          echo "For security reasons, the actual secrets cannot be displayed here."
          echo "Please review the secrets.json artifact and remove any sensitive data before merging."
          exit 1