name: Secret Detection
on: [pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install detect-secrets
        run: |
          pip install detect-secrets
          detect-secrets --version

      - name: Scan for secrets
        run: |
          detect-secrets scan --all-files -o secrets.json
          # Verificar si hay resultados y fallar explícitamente
          SECRETS_COUNT=$(jq -r '.results | length' secrets.json)
          if [ $SECRETS_COUNT -gt 0 ]; then
            echo "::error::Detectados $SECRETS_COUNT secretos en el código!"
            exit 1
          fi

      - name: Upload secrets report
        uses: actions/upload-artifact@v4
        if: always()  # Sube el reporte siempre, incluso si falló el paso anterior
        with:
          name: secrets-report
          path: secrets.json
