name: CI Pipeline - BankingSystem
on:
  pull_request:
    branches: [main]

jobs:
  detect_secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install detect-secrets
        run: pip install detect-secrets
          
      - name: Run detect-secrets scan
        run: |
          detect-secrets scan --all-files > secrets.json
          detect-secrets audit secrets.json
          
      - name: Upload secrets report
        uses: actions/upload-artifact@v3
        with:
          name: secrets-report
          path: secrets.json
