name: CI Pipeline - BankingSystem
on:
  pull_request:
    branches: [main]

jobs:
  detect_secrets:
    name: "Detect Secrets"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run detect-secrets (GitHub Action)
        uses: madhuakula/detect-secrets-action@v1.0.0  # Versión actualizada
        with:
          scan-path: .  # Escanea todo el repo
          fail-on-secrets: true  # Rompe el build si encuentra secretos
          output-file: secrets.json  # Exporta resultados

      - name: Upload secrets report
        uses: actions/upload-artifact@v3
        with:
          name: secrets-report
          path: secrets.json
