name: Secret Detection
on: [pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Scan for secrets (FAIL if found)
        run: |
          # Escanea y falla si hay secretos (exit code 1)
          detect-secrets scan --all-files --fail-on-any
          # Opcional: Genera el reporte igualmente
          detect-secrets scan --all-files > secrets.json

      - name: Upload secrets report (for review)
        if: always()  # Sube el reporte incluso si falla
        uses: actions/upload-artifact@v4
        with:
          name: secrets-report
          path: secrets.json

      - name: Fail if secrets found
        if: ${{ failure() }}
        run: |
          echo "::error::Secrets detected in code! Check 'secrets-report' artifact."
          exit 1
