name: CI Pipeline - BankingSystem
on:
  pull_request:
    branches: [main]

jobs:
  detect_secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run detect-secrets
        uses: madhuakula/detect-secrets-action@v0.1.0
        with:
          scan-path: .
          fail-on-secrets: true
          output-file: secrets.json
          
      - name: Upload secrets report
        uses: actions/upload-artifact@v3
        with:
          name: secrets-report
          path: secrets.json
