name: Secret Detection
on: [pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install detect-secrets
        run: |
          pip install detect-secrets
          detect-secrets --version

      - name: Scan and validate secrets
        run: |
          # Generar reporte incluso si falla el escaneo
          detect-secrets scan --all-files -o secrets.json || true
          
          # Validar existencia del archivo
          if [ ! -f secrets.json ]; then
            echo "::error::Error generando el reporte"
            exit 1
          fi
          
          # Contar secretos y fallar si hay resultados
          SECRETS_COUNT=$(jq -r '[.results | to_entries[] | .value[]] | length' secrets.json)
          if [ "$SECRETS_COUNT" -gt 0 ]; then
            echo "::error::🚫 Bloqueado - Se detectaron $SECRETS_COUNT secretos!"
            exit 1
          fi

      - name: Upload secrets report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secrets-report
          path: secrets.json
