name: CI - Detect Secrets

on:
  pull_request:
    branches:
      - main

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install necessary packages
        run: |
          pip install git+https://github.com/NASA-AMMOS/slim-detect-secrets.git@exp
          pip install jq
          
      - name: Create baseline if needed
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "⚠️ No baseline detected. Creating new one."
            mkdir empty-dir
            detect-secrets scan empty-dir > .secrets.baseline
            rm -r empty-dir
          fi

      - name: Scan and generate report
        id: scan
        run: |
          # Generate new scan
          detect-secrets scan --baseline .secrets.baseline --exclude-files '.secrets.*' --exclude-files '.git*' > secrets.json
          
          # Count findings
          FINDINGS=$(jq '.results | length' secrets.json)
          echo "findings=$FINDINGS" >> $GITHUB_OUTPUT

      - name: Upload secrets report
        uses: actions/upload-artifact@v4
        with:
          name: secrets-report
          path: secrets.json
          if-no-files-found: warn

      - name: Fail if secrets found
        if: steps.scan.outputs.findings != '0'
        run: |
          echo "::error::Potential secrets detected! Check artifacts for details."
          echo "Number of findings: ${{ steps.scan.outputs.findings }}"
          exit 1