name: Secret Detection
on: [pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install detect-secrets
        run: |
          pip install detect-secrets
          detect-secrets --version

      - name: Scan for secrets
        run: |
          # Genera el archivo incluso si falla el comando
          detect-secrets scan --all-files -o secrets.json || echo "Continuing after scan"
          
          # Verificar existencia del archivo
          if [ ! -f secrets.json ]; then
            echo "::error::No se generó el reporte de secretos"
            exit 1
          fi
          
          # Verificar contenido
          SECRETS_COUNT=$(jq -r '.results | length' secrets.json)
          if [ $SECRETS_COUNT -gt 0 ]; then
            echo "::error::Se detectaron $SECRETS_COUNT secretos!"
            exit 1
          fi

      - name: Upload secrets report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: secrets-report
          path: secrets.json
