name: CD Pipeline - Deploy to GitHub Packages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t banking-system .
          # Convertir el nombre del repositorio a minúsculas
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          # Etiquetar la imagen
          docker tag banking-system ghcr.io/${REPO_NAME}:latest
          docker tag banking-system ghcr.io/${REPO_NAME}:${{ github.sha }}

      - name: Push Docker image to GitHub Packages
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${REPO_NAME}:latest
          docker push ghcr.io/${REPO_NAME}:${{ github.sha }}